export const data = [
    {
      srNo: "1",
      DomainName: 'www.ebay.com',
      numberOfURL: 20,
      numberOfScreen: 50,
      annotationPercentage: '100%',
      annotationStatus: 'None',
      cssEditingPercentage: '90%',
      cssEditingStatus: 'None',
      numberOfComponent: 32,
      componentStatus: 'None',
    },
    {
      srNo: "2",
      DomainName: 'www.ebay.com',
      numberOfURL: 20,
      numberOfScreen: 50,
      annotationPercentage: '100%',
      annotationStatus: 'None',
      cssEditingPercentage: '90%',
      cssEditingStatus: 'None',
      numberOfComponent: 32,
      componentStatus: 'None',
    },
    {
      srNo: "3",
      DomainName: 'www.ebay.com',
      numberOfURL: 20,
      numberOfScreen: 50,
      annotationPercentage: '100%',
      annotationStatus: 'None',
      cssEditingPercentage: '90%',
      cssEditingStatus: 'None',
      numberOfComponent: 32,
      componentStatus: 'None',
    },
    {
      srNo: "4",
      DomainName: 'www.ebay.com',
      numberOfURL: 20,
      numberOfScreen: 50,
      annotationPercentage: '100%',
      annotationStatus: 'None',
      cssEditingPercentage: '90%',
      cssEditingStatus: 'None',
      numberOfComponent: 32,
      componentStatus: 'None',
    },
    {
      srNo: "5",
      DomainName: 'www.ebay.com',
      numberOfURL: 20,
      numberOfScreen: 50,
      annotationPercentage: '100%',
      annotationStatus: 'None',
      cssEditingPercentage: '90%',
      cssEditingStatus: 'None',
      numberOfComponent: 32,
      componentStatus: 'None',
    },
    // Add more data objects here as needed
  ];