export const data = [
    {
      srNo: "1",
      componentPack: 'Musical Store',
      category: 'E-Commerce',
      numberOfDomain: 3,
      numberOfURL: 20,
      numberOfScreen: 50,
      annotationPercentage: '100%',
      annotationStatus: 'None',
      cssEditingPercentage: '90%',
      cssEditingStatus: 'None',
      numberOfComponent: 32,
    },
    {
      srNo: "2",
      componentPack: 'Musical Store',
      category: 'E-Commerce',
      numberOfDomain: 3,
      numberOfURL: 20,
      numberOfScreen: 50,
      annotationPercentage: '100%',
      annotationStatus: 'None',
      cssEditingPercentage: '90%',
      cssEditingStatus: 'None',
      numberOfComponent: 32,
    },
    {
      srNo: "3",
      componentPack: 'Musical Store',
      category: 'E-Commerce',
      numberOfDomain: 3,
      numberOfURL: 20,
      numberOfScreen: 50,
      annotationPercentage: '100%',
      annotationStatus: 'None',
      cssEditingPercentage: '90%',
      cssEditingStatus: 'None',
      numberOfComponent: 32,
    },
    {
      srNo: "4",
      componentPack: 'Musical Store',
      category: 'E-Commerce',
      numberOfDomain: 3,
      numberOfURL: 20,
      numberOfScreen: 50,
      annotationPercentage: '100%',
      annotationStatus: 'None',
      cssEditingPercentage: '90%',
      cssEditingStatus: 'None',
      numberOfComponent: 32,
    }
    // Add more data objects here as needed
  ];