export const data = [
    {
      srNo: 1,
      urllink: 'www.ebay.com/payments/ebaypay/payflowpro/aaaaaaaaaaaaaaaaaaaaaa',
      numberOfScreen: 50,
      annotationPercentage: '100%',
      annotationStatus: 'None',
      cssEditingPercentage: '90%',
      cssEditingStatus: 'None',
      numberOfComponent: 32,
      componentStatus: 'None',
    },
    {
      srNo: 2,
      urllink: 'www.ebay.com',
      numberOfScreen: 50,
      annotationPercentage: '100%',
      annotationStatus: 'None',
      cssEditingPercentage: '90%',
      cssEditingStatus: 'None',
      numberOfComponent: 32,
      componentStatus: 'None',
    },
    {
      srNo: 3,
      urllink: 'www.ebay.com',
      numberOfScreen: 50,
      annotationPercentage: '100%',
      annotationStatus: 'None',
      cssEditingPercentage: '90%',
      cssEditingStatus: 'None',
      numberOfComponent: 32,
      componentStatus: 'None',
    },
    {
      srNo: 4,
      urllink: 'www.ebay.com',
      numberOfScreen: 50,
      annotationPercentage: '100%',
      annotationStatus: 'None',
      cssEditingPercentage: '90%',
      cssEditingStatus: 'None',
      numberOfComponent: 32,
      componentStatus: 'None',
    },
    {
      srNo: 5,
      urllink: 'www.ebay.com',
      numberOfScreen: 50,
      annotationPercentage: '100%',
      annotationStatus: 'None',
      cssEditingPercentage: '90%',
      cssEditingStatus: 'None',
      numberOfComponent: 32,
      componentStatus: 'None',
    },
    {
      srNo: 6,
      urllink: 'www.ebay.com',
      numberOfScreen: 50,
      annotationPercentage: '100%',
      annotationStatus: 'None',
      cssEditingPercentage: '90%',
      cssEditingStatus: 'None',
      numberOfComponent: 32,
      componentStatus: 'None',
    }
    
    // Add more data objects here as needed
  ];